# pw.Models.FonctionsJudo.dcm.yml

pw\Models\FonctionsJudo:

  type: entity
  table: fonctions_judo

  oneToMany:
    sportif:
      targetEntity: adherent_sportif
      mappedby: fonctions

  manyToOne:
    sportif:
      targetEntity: fonctions_judo
      inversedBy: sportif
      joinColumn:
        name: no_adherent
        referencedColumnName: id

  fields:
    arbitre_f1:
      type: string
      column: arbitre_f1
      nullable: true
      options:
        default: null

    arbitre_f2:
      type: string
      column: arbitre_f2
      nullable: true
      options:
        default: null

    arbitre_f3:
      type: string
      column: arbitre_f3
      nullable: true
      options:
        default: null

    arbitre_f4:
      type: string
      column: arbitre_f4
      nullable: true
      options:
        default: null

    arbitre_f5A:
      type: string
      column: arbitre_f5A
      nullable: true
      options:
        default: null

    arbitre_f5B:
      type: string
      column: arbitre_f5B
      nullable: true
      options:
        default: null

    com_sportif_n1:
      type: string
      column: com_sportif_n1
      nullable: true
      options:
        default: null

    com_sportif_n2:
      type: string
      column: com_sportif_n2
      nullable: true
      options:
        default: null

    com_sportif_n3:
      type: string
      column: com_sportif_n3
      nullable: true
      options:
        default: null

    com_sportif_n4:
      type: string
      column: com_sportif_n4
      nullable: true
      options:
        default: null

    fonctions_codep:
      type: string
      column: fonctions_codep
      nullable: true
      options:
        default: null

    fonctions_ligue_regionale:
      type: string
      column: fonctions_ligue_regionale
      nullable: true
      options:
        default: null

    fonction_autre:
      type: string
      column: fonction_autre
      nullable: true
      options:
        default: null

    recompense:
      type: string
      column: recompense
      nullable: true
      options:
        default: null
